<a href="https://colab.research.google.com/github/sytluc0803/MSSP607/blob/main/Modules/Week_4/Week_4_Ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
from google.colab import userdata
import os

github_token = userdata.get('Git_Key')
owner = 'sytluc0803'
repository = 'MSSP607'

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])

# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print(f"Changed directory to: {os.getcwd()}")

Changed directory to: /content/MSSP607

In [3]:
%pushd "/content/MSSP607/Modules/Week_4"

/content/MSSP607/Modules/Week_4

['/content/MSSP607']

In [4]:
!ls

parsed.csv  README.md  Week_4_Ex.ipynb

In [18]:
import numpy as np
import pandas as pd
import statistics

df = pd.read_csv('parsed.csv')
df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,parsed_place
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,California
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,California
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...,California
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...,California
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...,California

In [23]:
## Q1
q1 = df[(df['magType'] == 'mb') & (df['parsed_place'] == 'Japan')& (df['type']=='earthquake')]
q1.head()

Q1 = statistics.quantiles(q1['mag'], n=100)
Q1

print(Q1[94])

4.9

In [25]:
## Q2
Indo = df[(df['parsed_place'] == 'Indonesia') & (df['type']=='earthquake')]
Indo.head()

Q2 = Indo["tsunami"].mean()
print(Q2)

0.23129251700680273

In [19]:
## Q3
Nev = df[(df['type'] == 'earthquake') & (df['parsed_place'] == 'Nevada')]
Nev.columns

Nev.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,14.000000,647.000000,14.000000,647.000000,647.000000,1.00,647.000000,647.000000,647.000000,6.470000e+02,647.0,647.0,6.470000e+02
mean,2.421429,0.163155,2.500000,154.436615,0.437311,2.84,12.704791,0.140627,9.146832,1.538318e+12,0.0,-480.0,1.538409e+12
std,0.514675,0.161793,4.783787,69.474945,0.653397,NaN,10.052695,0.056765,17.939055,5.954980e+08,0.0,0.0,5.991682e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537323e+12
25%,2.000000,0.053000,1.000000,97.295000,-0.100000,2.84,6.000000,0.104400,0.000000,1.537859e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.109000,1.000000,150.040000,0.300000,2.84,9.000000,0.142900,1.000000,1.538286e+12,0.0,-480.0,1.538428e+12
75%,3.000000,0.223000,1.000000,200.515000,0.800000,2.84,16.000000,0.181050,10.000000,1.538824e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.340000,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

In [52]:
## Q4
df['parsed_place'].unique()

places = [
    "Bolivia", "Chile", "Ecuador", "Peru", "Costa Rica", "Guatemala",
    "Mexico", "Japan", "Philippines", "Indonesia", "New Zealand",
    "Antarctic", "Canada", "Fiji", "Alaska", "Washington", "California",
    "Russia", "Taiwan", "Tonga", "Kermadec"
]

pattern = "|".join(places) ## prep the list for string mapping

df2 = df
df2["Ring of Fire"] = (
    df2["parsed_place"]
    .str.contains(pattern, case=False, na=False)
    .astype(int)
)
## overwriting the "New Mexico" variable in "Ring of Fire"
df2.loc[
    df2["parsed_place"].str.contains("New Mexico", case=False, na=False),
    "Ring of Fire"
] = 0

df2.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,time,title,tsunami,type,types,tz,updated,url,parsed_place,Ring of Fire
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,California,1
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,California,1
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...,California,1
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...,California,1
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...,California,1

In [47]:
## Q5
df3 = df2[df['type']== "earthquake"]
Q5 = df3['Ring of Fire'].value_counts()
print(Q5)

Ring of Fire
1    7004
0    2077
Name: count, dtype: int64

In [53]:
## Q6
Q6 = pd.crosstab(df3["Ring of Fire"], df3["tsunami"])
print(Q6)

## In all the Ring of Fire region, 45 of the quakes have tsunami with them.

tsunami          0   1
Ring of Fire
0             2061  16
1             6959  45