<a href="https://colab.research.google.com/github/sytluc0803/MSSP607/blob/main/Modules/Week_6/Week_6_Ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import userdata
import os

github_token = userdata.get('Git_Key')
owner = 'sytluc0803'
repository = 'MSSP607'

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])

# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print(f"Changed directory to: {os.getcwd()}")

Changed directory to: /content/MSSP607

In [2]:
%pushd "/content/MSSP607/Modules/Week_6"

/content/MSSP607/Modules/Week_6

['/content/MSSP607']

In [3]:
!ls

 README.rmd  'Student Performance Data.csv'

In [6]:
import pandas as pd
df = pd.read_csv('Student Performance Data.csv')
df.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [8]:
# add a score_category that assign different score range to different grades
df["score_category"] = df["total score"].apply(
    lambda x: "Excellent" if x >= 270
    else "Good" if x >= 230
    else "Average" if x >= 180
    else "Needs improvement"
)

df.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect,score_category
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium,Average
1,female,group C,some college,standard,69,90,88,247,completed,high,Good
2,female,group B,master's degree,standard,90,95,93,278,none,high,Excellent
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low,Needs improvement
4,male,group C,some college,standard,76,78,75,229,none,high,Average